### ISSUE TITLE
Build status badge in README is broken due to repo name (".com" is extra)

### ISSUE THREAD

**Issue by mbrukman** [christophM/modeling-mindsets#15]
Thank you for writing this book and sharing a free version of it with us!

I noticed that the current build status image in the [`README.md`](https://github.com/christophM/modeling-mindsets/blob/c843700488fb6eaf829bccecf138e72361613d60/README.md#L8):

https://github.com/christophM/modeling-mindsets/blob/c843700488fb6eaf829bccecf138e72361613d60/README.md#L8

appears to be rendering incorrectly:

![Build Status](https://github.com/christophM/modeling-mindsets.com/actions/workflows/Book.yaml/badge.svg)

because the repository name is "modeling-mindsets.com" but the actual repository name is "modeling-mindsets" (without `.com`). Fixing the repo name makes the badge render as expected:

![Build Status](https://github.com/christophM/modeling-mindsets/actions/workflows/Book.yaml/badge.svg)

_Note: usually, I would just submit a PR to fix this directly instead filing it as an issue, but the chosen license (CC-BY-NC-SA) makes this complicated, sorry. BTW, that's not to imply there's anything wrong with your chosen license; I totally understand and not suggesting you change it! It makes a lot of sense for this case._

**Comment by christophM** [comment]
Thanks!

License-wise it should be fine. CC-BY is only for the rendered book. The rest is MIT licensed. https://github.com/christophM/modeling-mindsets/blob/main/LICENSE.txt
